// client/src/App.tsx
import React, { useState } from 'react';
import logo from './logo.svg';
import './App.css';

interface Props {
  params: string[]
}

function App(props: Props | undefined) {

  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
        <button onClick={() => setCount(count +1)}>{count}</button>
        
        {
          props?.params ?

          <div className="paramsContainer">
            <ul>
              { props?.params?.map((elem, i) => <li key={i}>{elem}</li>) }
            </ul>
          </div>
          : null
        }
        
      </header>
    </div>
  );
}

export default App;

// examples/vite-solid/src/App.tsx
import { createSignal } from 'solid-js'
import './App.css'
import solidLogo from './assets/solid.svg'
import viteLogo from '/vite.svg'

function App() {
  const [count, setCount] = createSignal(0)

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} class="logo" alt="Vite logo" />
        </a>
        <a href="https://solidjs.com" target="_blank">
          <img src={solidLogo} class="logo solid" alt="Solid logo" />
        </a>
      </div>
      <h1>Vite + Solid</h1>
      <div class="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count()}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p class="read-the-docs">
        Click on the Vite and Solid logos to learn more
      </p>
    </>
  )
}

export default App
